#!/bin/bash

BRANCH=$(git symbolic-ref HEAD)

grep '^refs #[0-9]\+: ' $1
if [ $? -eq 0 ]; then
  exit
fi

ISSUE=$(echo $BRANCH | sed -e 's/^.*-id-\([0-9]*\)$/#\1/')
if [ "$ISSUE" != "$BRANCH" ]; then
  echo "Auto append: $ISSUE"
  mv $1 $1.$$
  echo -n "$ISSUE: " > $1
  cat $1.$$ >> $1
  rm $1.$$
fi
