#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH=$PATH:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/opt/openssl/bin:/usr/local/opt/texinfo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/bin:/usr/sbin:/bin:/sbin
# PATH under the home directory
export PATH=$PATH:$HOME/.bin:$HOME/bin/:$HOME/.local/bin:$HOME/gprog/garaemon-settings/scripts/utils

# On mac os x, emacsclient is availale under Emacs.app.
if [ -e /Applications/Emacs.app/Contents/MacOS/bin ]; then
  export PATH=/Applications/Emacs.app/Contents/MacOS/bin:$PATH
fi


export TRAMP_ZSHENV_LOADED="yes"
