- name: Get latest hub version
  shell: >
    curl -sI https://github.com/github/hub/releases/latest | awk -F '/' '/^location:/{print $NF}'
  register: hub_latest_version

- name: Get latest hub version number
  shell: echo {{hub_latest_version.stdout}} | sed 's/^v//g'
  register: hub_latest_version_number


- name: Set OS Name (darwin)
  set_fact:
    os_name: "darwin"
  when: ansible_os_family == "Darwin"

- name: Set Arch Name (darwin)
  command: echo amd64
  register: arch
  when: ansible_os_family == "Darwin"

- name: Set OS Name (debian)
  set_fact:
    os_name: "linux"
  when: ansible_os_family == "Debian"

- name: Set Arch Name (darwin)
  command: dpkg --print-architecture
  when: ansible_os_family == "Debian"
  register: arch

- name: Download latest hub {{hub_latest_version.stdout}}
  get_url:
    url: https://github.com/github/hub/releases/download/{{hub_latest_version.stdout}}/hub-{{os_name}}-{{arch.stdout}}-{{hub_latest_version_number.stdout}}.tgz
    dest: /tmp/hub.tgz
  register: download_hub

- name: Extract hub
  when: download_hub.changed
  command: tar xvzf /tmp/hub.tgz chdir=/tmp/

- name: Create .local/bin
  file:
    path: ~/.local/bin
    state: directory

- name: Copy to .local/bin/
  when: download_hub.changed
  command: cp /tmp/hub-{{os_name | lower}}-{{arch.stdout}}-{{hub_latest_version_number.stdout}}/bin/hub ~/.local/bin/hub

- name: chmod hub
  when: download_hub.changed
  file:
    path: ~/.local/bin/hub
    mode: 0755

- name: Prepare completions directory
  file:
    path: ~/.completions
    state: directory

- name: Install hub completion
  get_url:
    url: https://raw.githubusercontent.com/github/hub/master/etc/hub.zsh_completion
    dest: ~/.completions/_hub
