- name: "Clone cquery"
  git:
    repo: https://github.com/cquery-project/cquery.git
    dest: ~/gprog/cquery
- name: "Create build directory"
  file:
    path: ~/gprog/cquery/build
    state: directory
- name: "Run cmake for cquery"
  command: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=release -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -DCMAKE_INSTALL_PREFIX=$HOME/.local
  args:
    chdir: ~/gprog/cquery/build
- name: "Build cquery"
  command: cmake --build .
  args:
    chdir: ~/gprog/cquery/build
- name: "Install cquery"
  command: cmake --build . --target install
  args:
    chdir: ~/gprog/cquery/build
