- name: Download install script
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    dest: /tmp/nvm_install.sh
    mode: 0755
- name: Install nvm
  command: bash /tmp/nvm_install.sh
- name: Install node {{node_versions}}
  command: bash -lc "source ~/.nvm/nvm.sh && nvm install v{{item}}"
  loop: "{{node_versions}}"
