language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    recipients:
      - garaemon@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always
install:
  - sudo /etc/init.d/postgresql stop
  - ./scripts/install.sh
