language: generic
dist: xenial
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ansible/ansible'
    packages:
      - ansible
      - dirmngr                 # Required by gpg command
script:
  - ansible --version
  - ansible-playbook main.yml -i "localhost," -c local --become
