- hosts: all
  roles:
    - base
    - sudo-no-password
    - git
    - git-find-big
    - vim
    - tmux
    - zsh
    - starship
    - role: apt
      when: ansible_os_family == "Debian"
    - role: homebrew
      when: ansible_os_family == "Darwin"
    - uv
    - clang-format
    - gh
    - emacs
    - peco
    - nvm
    - font
    - ispell
    - tig
    - dircolors-solarized
    - role: base16-gnome-terminal
      when: ansible_os_family == "Debian"
    - role: dictd
      when: ansible_os_family == "Debian"
    - role: vscode
      when:
        - ansible_os_family == "Debian"
        - ansible_architecture != 'aarch64'
    - python-language-server
    - typescript-language-server
    - ghostty
  vars:
    build_emacs: true
