- hosts: all
  roles:
    - base
    - cpplint
    - clang-format
    - git-find-big
    - vim
    - tmux
    - zsh
    - emacs
    - powerline
    - role: zlib
      when: ansible_os_family == "Darwin"
    - role: apt
      when: ansible_os_family == "Debian"
    - role: homebrew
      when: ansible_os_family == "Darwin"
    - peco
    - role: chrome
      when: ansible_os_family == "Debian"
      become: yes
    - hub
    - pyenv
    - rvm
    - nvm
    - font
    - ispell
    - tig
    - dircolors-solarized
    - role: base16-gnome-terminal
      when: ansible_os_family == "Debian"
    - role: dictd
      when: ansible_os_family == "Debian"
    - inkdrop
    - vscode
    - cquery
    - clangd
    - python-language-server
    - typescript-language-server
    - iterm2-themes
  vars:
    # pyenv variables
    # Initialize shell profile scripts
    pyenv_init_shell: yes
    # Python versions to install
    pyenv_python_versions:
      - "2.7.10"
      - "3.7.2"
    # Set global pyenv version
    pyenv_global: "system"
    # Define the shell profile scripts to initialiaze
    pyenv_shell_profile_scripts:
      - .bashrc
      - .zshrc
    # rvm variables
    rvm1_rubies:
      - 'ruby-2.6.0'
    rvm1_user: '{{ansible_env.USER}}'
    rvm1_install_flags: '--user-install'
