- hosts: all
  roles:
    - base
    - vim
    - tmux
    - zsh
    - emacs
    - powerline
    - zlib
    - role: apt
      when: ansible_os_family == "Debian"
    - role: homebrew
      when: ansible_os_family == "Darwin"
    - pyenv
    - rvm
    - nvm
    - font
    - ispell
    - peco
  vars:
    # pyenv variables
    # Initialize shell profile scripts
    pyenv_init_shell: yes
    # Python versions to install
    pyenv_python_versions:
      - "2.7.10"
      - "3.7.2"
    # Set global pyenv version
    pyenv_global: "3.7.2"
    # Define the shell profile scripts to initialiaze
    pyenv_shell_profile_scripts:
      - .bashrc
      - .zshrc
    # rvm variables
    rvm1_rubies:
      - 'ruby-2.6.0'
    rvm1_user: '{{ansible_env.USER}}'
