- name: Apply base settings to all hosts
  hosts: all
  roles:
    - role: apt
      when: ansible_facts.os_family == "Debian"
    - role: homebrew
      when: ansible_facts.os_family == "Darwin"
    - mise
    - ghq
    - base
    - sudo_no_password
    - git
    - git_find_big
    - starship
    - coding_agent
    - agg
    - uv
    - clang_format
    - gh
    - emacs
    - peco
    - role: font
      when: ansible_facts.os_family == "Debian"
    - ispell
    - enchant
    - dircolors_solarized
    - role: base16_gnome_terminal
      when: ansible_facts.os_family == "Debian"
    - role: dictd
      when: ansible_facts.os_family == "Debian"
    - role: keyboard
      when: ansible_facts.os_family == "Debian"
    - role: keyd
      when: ansible_facts.os_family == "Debian"
    - role: chrome
      when: ansible_facts.os_family == "Debian" and ansible_facts.architecture == "x86_64"
    - python_language_server
    - typescript_language_server
    - ghostty_install
    - ghostty
    - karabiner
  vars:
    emacs_build_emacs: true
