- name: Apply base settings to all hosts
  hosts: all
  roles:
    - base
    - sudo_no_password
    - git
    - git_find_big
    - vim
    - tmux
    - zsh
    - starship
    - claude
    - role: apt
      when: ansible_os_family == "Debian"
    - role: homebrew
      when: ansible_os_family == "Darwin"
    - uv
    - mise
    - clang_format
    - gh
    - emacs
    - peco
    - role: font
      when: ansible_os_family == "Debian"
    - ispell
    - tig
    - dircolors_solarized
    - role: base16_gnome_terminal
      when: ansible_os_family == "Debian"
    - role: dictd
      when: ansible_os_family == "Debian"
    - role: vscode
      when:
        - ansible_os_family == "Debian"
        - ansible_architecture != 'aarch64'
    - python_language_server
    - typescript_language_server
    - ghostty
    - karabiner
  vars:
    emacs_build_emacs: true
