- hosts: all
  roles:
    - base
    - sudo-no-password
    - cpplint
    - clang-format
    - git
    - git-find-big
    - vim
    - tmux
    - zsh
    - starship
#    - role: zlib
#      when: ansible_os_family == "Darwin"
    - role: apt
      when: ansible_os_family == "Debian"
    - role: homebrew
      when: ansible_os_family == "Darwin"
    - emacs
    - peco
    - role: chrome
      when:
        - ansible_os_family == "Debian"
        - ansible_architecture != 'aarch64'
      become: yes
    - gh
    - pyenv
    - nvm
    - font
    - ispell
    - tig
    - dircolors-solarized
    - role: base16-gnome-terminal
      when: ansible_os_family == "Debian"
    - role: dictd
      when: ansible_os_family == "Debian"
    - inkdrop
    - role: vscode
      when:
        - ansible_os_family == "Debian"
        - ansible_architecture != 'aarch64'
    - python-language-server
    - typescript-language-server
    - ghostty
    # - rvm
  vars:
    # pyenv variables
    # Initialize shell profile scripts
    pyenv_init_shell: yes
    # Python versions to install
    pyenv_python_versions:
      - "3.9.4"
    # Set global pyenv version
    pyenv_global: "system"
    # Define the shell profile scripts to initialiaze
    pyenv_shell_profile_scripts:
      - .bashrc
      - .zshrc
    # rvm variables
    rvm1_rubies:
      - 'ruby-2.6.0'
    rvm1_user: '{{ansible_env.USER}}'
    rvm1_install_flags: '--user-install'
