- hosts: all
  roles:
    - base
    - git
    - git-find-big
    - vim
    - tmux
    - zsh
    - starship
    - uv
    - peco
    - nvm
    - ispell
    - tig
    - dircolors-solarized
    - ghostty
    # - role: base16-gnome-terminal
    #   when: ansible_os_family == "Debian"
    # - role: dictd
    #   when: ansible_os_family == "Debian"
