- name: Apply minimal settings to all hosts
  hosts: all
  roles:
    - base
    - git
    - git_find_big
    - vim
    - tmux
    - zsh
    - starship
    - claude
    - uv
    - mise
    - peco
    - ispell
    - tig
    - dircolors_solarized
    - ghostty
    - karabiner
    # - role: base16_gnome_terminal
    #   when: ansible_os_family == "Debian"
    # - role: dictd
    #   when: ansible_os_family == "Debian"
