- hosts: all
  roles:
    - base
    - git-find-big
    - vim
    - tmux
    - zsh
    - peco
    - pyenv
    - nvm
    - ispell
    - tig
    - dircolors-solarized
    - role: base16-gnome-terminal
      when: ansible_os_family == "Debian"
    - role: dictd
      when: ansible_os_family == "Debian"
    - inkdrop

    # - rvm
  vars:
    # pyenv variables
    # Initialize shell profile scripts
    pyenv_init_shell: yes
    # Python versions to install
    pyenv_python_versions:
      - "3.9.4"
    # Set global pyenv version
    pyenv_global: "system"
    # Define the shell profile scripts to initialize
    pyenv_shell_profile_scripts:
      - .bashrc
      - .zshrc
