- name: Apply minimal settings to all hosts
  hosts: all
  roles:
    - mise
    - ghq
    - base
    - git_find_big
    - vim
    - tmux
    - zsh
    - starship
    - coding_agent
    - uv
    - ghostty_install
    - peco
    - ispell
    - enchant
    - tig
    - dircolors_solarized
    - ghostty
    - karabiner
    - role: font
      when: ansible_facts.os_family == "Debian"
    # - role: base16_gnome_terminal
    #   when: ansible_facts.os_family == "Debian"
    # - role: dictd
    #   when: ansible_facts.os_family == "Debian"
