- name: Get ghq root directory
  shell: |
    eval "$({{ ansible_env.HOME }}/.local/bin/mise activate bash)"
    ghq root
  args:
    executable: /bin/bash
  register: ccls_ghq_root
  changed_when: false
  failed_when: false

- name: Set ghq root path
  set_fact:
    ccls_ghq_root_path: "{{ ccls_ghq_root.stdout if ccls_ghq_root.rc == 0 else ansible_env.HOME + '/ghq' }}"

- name: Clone ccls using ghq
  shell: |
    eval "$({{ ansible_env.HOME }}/.local/bin/mise activate bash)"
    ghq get https://github.com/MaskRay/ccls.git
  args:
    executable: /bin/bash

- name: Create build directory
  file:
    path: "{{ ccls_ghq_root_path }}/github.com/MaskRay/ccls/build"
    state: directory
- name: Install clang
  apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
      - clang-10
      - libclang-10-dev
- name: Configure ccls
  command: >-
    cmake -H..
        -BRelease
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_PREFIX_PATH=/usr/lib/llvm-10
        -DLLVM_INCLUDE_DIR=/usr/lib/llvm-10/include
        -DLLVM_BUILD_INCLUDE_DIR=/usr/include/llvm-10/
        -DCMAKE_INSTALL_PREFIX=$HOME/.local
  args:
    chdir: "{{ ccls_ghq_root_path }}/github.com/MaskRay/ccls/build"
- name: Build and install ccls
  command: cmake --build Release --target install
  args:
    chdir: "{{ ccls_ghq_root_path }}/github.com/MaskRay/ccls/build"
