- name: Clone ccls
  ansible.builtin.git:
    repo: https://github.com/MaskRay/ccls.git
    dest: ~/gprog/ccls
- name: Create build directory
  ansible.builtin.file: 
    path: ~/gprog/ccls/build
    state: directory
- name: Install clang
  ansible.builtin.apt: 
    name: "{{packages}}"
    state: present
  become: true
  vars:
    packages:
      - clang-10
      - libclang-10-dev
- name: Configure ccls
  ansible.builtin.command: >-
    cmake -H..
        -BRelease
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_PREFIX_PATH=/usr/lib/llvm-10
        -DLLVM_INCLUDE_DIR=/usr/lib/llvm-10/include
        -DLLVM_BUILD_INCLUDE_DIR=/usr/include/llvm-10/
        -DCMAKE_INSTALL_PREFIX=$HOME/.local
  args:
    chdir: ~/gprog/ccls/build
- name: Build and install ccls
  ansible.builtin.command: cmake --build Release --target install
  args:
    chdir: ~/gprog/ccls/build
