- name: Install clang-format
  ansible.builtin.apt: 
    name:
      - clang-format
  become: true
  when: ansible_os_family == "Debian"

- name: Copy ~/.clang-format file
  copy:
    src: clang-format
    dest: ~/.clang-format
