# Based on https://code.visualstudio.com/docs/setup/linux

- name: Create tempfile for microsoft.asc
  tempfile:
    state: file
    suffix: microsoft_asc
  register: vscode_microsoft_asc_tempfile

- name: Download microsoft.asc
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: "{{ vscode_microsoft_asc_tempfile.path }}"
  register: vscode_microsoft_asc_download

- name: Create tempfile for microsoft.gpg
  tempfile:
    state: file
    suffix: microsoft_gpg
  register: vscode_microsoft_gpg_tempfile

- name: Convert microsoft.asc to gpg
  command: "gpg --dearmor -o {{ vscode_microsoft_gpg_tempfile.path }} {{ vscode_microsoft_asc_tempfile.path }}"
  args:
    creates: "{{ vscode_microsoft_gpg_tempfile.path }}"
  when: vscode_microsoft_asc_download.changed

- name: Install microsoft.gpg
  command:
    install -o root -g root -m 644 "{{ vscode_microsoft_gpg_tempfile.path }}" /etc/apt/trusted.gpg.d/
  become: true
  when: vscode_microsoft_asc_download.changed # Only run if gpg file was (re)created

- name: Add microsoft apt repository
  lineinfile:
    line: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    path: /etc/apt/sources.list.d/vscode.list
    create: true
  become: true

- name: Install apt-transport-https
  apt:
    name:
      - apt-transport-https
  become: true

- name: Install vscode
  apt:
    name:
      - code
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"
