# -*- mode: shell-script -*-
# -*- coding: utf-8 -*-
umask 022

export PATH=$PATH:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin


export LC_ALL=en_US.UTF-8

#zsh
autoload -U colors
colors
autoload -U compinit
compinit
setopt correct
setopt beep

setopt list_types
setopt auto_list
setopt auto_menu
setopt magic_equal_subst
setopt auto_cd
setopt auto_param_keys
setopt pushd_ignore_dups
setopt auto_pushd

watch="all"
log

local GREEN=$'%{\e[1;32m%}'
local YELLOW=$'%{\e[1;33m%}'
local BLUE=$'%{\e[1;34m%}'
local LIGHT_BLUE=$'%{\e[1;36m%}'
local DEFAULT=$'%{\e[1;0m%}'


HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_dups     # ignore duplication command history list
setopt share_history        # share command history data
bindkey -e

#alias
alias ls="ls --color=auto"
alias cp='cp -v'
alias mv='mv -v'
alias grep='grep --color=auto'

#ssh-agent
# you always need to cal init_ssh_agent when you want to activate ssh-agent
init_ssh_agent () {
    eval `ssh-agent`
    mkdir -p $HOME/.tmp/ssh-agent/
    ssh-add
    if [ $? = "0" ]; then
        local agent="$HOME/.tmp/ssh-agent/`hostname`_local"
        ln -snf "$SSH_AUTH_SOCK" $agent && export SSH_AUTH_SOCK=$agent
    else
        echo "init failed"
        return 1
    fi
}

update_ssh_agent () {
    update_ssh_agent_ "$HOME/.tmp/ssh-agent/`hostname`_local" \
        || update_ssh_agent_ "$HOME/.tmp/ssh-agent/`hostname`"
}

update_ssh_agent_ () {
    local agent="$1"
    if [ -z "$agent" ]; then
        return 1
    fi

    if [ -S "$agent" ]; then
        if [ ! "$SSH_AUTH_SOCK" -ef "$agent" ]; then
            export SSH_AUTH_SOCK_OLD=$SSH_AUTH_SOCK
        fi

        export SSH_AUTH_SOCK=$agent
        return 0
    elif [ ! -S "$SSH_AUTH_SOCK" ]; then
        echo "no ssh-agent"
        if [ -L "$agent" ]; then
            rm -rf $agent
        fi
        if [ -n "$SSH_AUTH_SOCK_OLD" ]; then
            if [ -S "$SSH_AUTH_SOCK_OLD" ]; then
                SSH_AUTH_SOCK=$SSH_AUTH_SOCK_OLD
            fi
            unset SSH_AUTH_SOCK_OLD
            update_ssh_agent
        fi
    elif [ ! -L "$SSH_AUTH_SOCK" ]; then
        ssh-add -l >/dev/null \
            && ln -snf "$SSH_AUTH_SOCK" $agent && export SSH_AUTH_SOCK=$agent
    fi
}


# X Window Setup
function get_xserver ()
{
    case $TERM in
        xterm )
            XSERVER=$(who am i | awk '{print $NF}' | tr -d ')''(' ) 
            XSERVER=${XSERVER%%:*}
            ;;
        aterm | rxvt)
        # find some code that works here.....
            ;;
    esac  
}

if [ -z ${DISPLAY:=""} ]; then
    get_xserver
    if [[ -z ${XSERVER}  || ${XSERVER} == $(hostname) || ${XSERVER} == "unix" ]]; then 
        DISPLAY=":0.0"          # Display on local host
    else                
        DISPLAY=${XSERVER}:0.0  # Display on remote host
    fi
fi

export DISPLAY

# PATH setup
export PYTHONPATH=$PYTHONPATH:$HOME/gprog/scan-scripts
export PATH=$PATH:$HOME/gprog/scan-scripts/bin
if [ -e $HOME/.zshrc.jsk ]; then
    echo loading jsk setup file ...
    source $HOME/.zshrc.jsk
fi

OS=`uname`
if [ "$OS" = "CYGWIN_NT-5.1" -o "$OS" = "CYGWIN_NT-6.0" ] ; then
    if [ -e $HOME/.zshrc.cygwin ]; then
        echo loading cygwin setup file ...
        source $HOME/.zshrc.cygwin
    fi
    if [ -e $HOME/.zshrc.cygwin.jsk ]; then
        echo loading jsk setup file ...
        source $HOME/.zshrc.cygwin.jsk
    fi
elif [ "$OS" = "Linux" ] ; then
    if [ -e $HOME/.zshrc.linux ]; then
        echo loading linux setup file ...
        source $HOME/.zshrc.linux
    fi
elif [ "$OS" = "Darwin" ] ; then
    if [ -e $HOME/.zshrc.darwin ]; then
        echo loading darwin setup file ...
        source $HOME/.zshrc.darwin
    fi
fi

# customizing zshrc?
if [ -e $HOME/.zshrc.mine ]; then
    echo loading customizing setup file ...
    source $HOME/.zshrc.mine
fi


#alias rm='trash-put -v'

# export CC="ccache gcc"
# export CXX="ccache g++"

alias wifi-diag="open '/System/Library/CoreServices/Wi-Fi Diagnostics.app'"
#alias pygmentize="pygmentize-2.7"
alias eclient='emacs-client -n'

export PATH=$PATH:$HOME/gprog/platex-create-pkg
export PATH=$PATH:$HOME/gprog/spark
#alias jbibtex=bibtex

export PATH=$PATH:$HOME/gprog/emacs-settings

export CC=gcc
source $HOME/.nvm/nvm.sh

alias titanium="$HOME/Library/Application\ Support/Titanium/mobilesdk/osx/1.7.5/titanium.py"
export PATH=/opt/android-sdk/tools:$PATH
export PATH=/opt/android-sdk/tools:$PATH

nvm use v0.10.21                  # for heroku
export NODE_PATH=~/.nvm/v0.10.3/lib/node_modules

[ -s ${HOME}/.rvm/scripts/rvm ] && source ${HOME}/.rvm/scripts/rvm


# function chpwd() {
#     echo chpwd
#     if [ `echo $EMACS | grep -c "term"` -eq 1 ]; then
#         echo '\\\033AnSiTc' $PWD
#     fi
# }
# export LANG="ja_JP.utf-8"
export PATH=$PATH:$HOME/gprog/git-your-emacs

export PATH=$PATH:$HOME/gprog/heroku-nodekit


export PATH=$PATH:/usr/local/Cellar/pypy/1.9/bin/

fpath=($HOME/.zsh/functions/ $fpath) # not work?


# export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export PATH=$PATH:$HOME/gprog/minify-make

export SENCHA_SDK_TOOLS_2_0_0_BETA3=/Applications/SenchaSDKTools-2.0.0-beta3
export PATH=$PATH:$SENCHA_SDK_TOOLS_2_0_0_BETA3

export PATH=$PATH:$HOME/gprog/jq

#ROS
function change_ros_setup() {
    local prefix_path=$1
    if [ -e $prefix_path/setup.zsh ]; then
        source $prefix_path/setup.zsh
    fi
    export CATKIN_WS=$prefix_path
    if [ -e `rospack find hrpsys_gazebo_tutorials`/setup.sh ]; then
        source `rospack find hrpsys_gazebo_tutorials`/setup.sh
    fi
    export ROS_WORKSPACE=`dirname $prefix_path`
}

function catmake() {
    local catkin_pkg
    if [ -e package.xml ]; then
        catkin_pkg=`basename $PWD`
        (cd $ROS_WORKSPACE && source /opt/ros/$ROS_DISTRO/setup.zsh && catkin_make $@ --only-pkg-with-deps $catkin_pkg)
    else
        (cd $ROS_WORKSPACE && source /opt/ros/$ROS_DISTRO/setup.zsh && catkin_make $@)
    fi
    
    local result=$?
    if [ $result ] ; then
        t update "[success!!] catkin_make $* [`date`]" > /dev/null
    else
        t update "[failed!!] catkin_make $* [`date`]" > /dev/null
    fi
    return $result
}

function _catmake() {
    local options
    options="install test clean -h -C --source --build --force-cmake --no-color --pkg \
--only-pkg-with-deps --cmake-args --make-args \
`rospack list | cut -f1 -d' '`"
    reply=(${=options})
}

compctl -K "_catmake" "catmake"

function roshydro() {
    change_ros_setup $HOME/ros/hydro/install
    export PATH=$PATH:`rospack find roseus`/bin
}

function roshydrodev() {
    change_ros_setup $HOME/ros/hydro/devel
    export PATH=$PATH:`rospack find roseus`/bin
}

function rosgroovy() {
    change_ros_setup $HOME/ros/groovy/
    export PATH=$PATH:`rospack find roseus`/bin
}

function rosgroovydev() {
    change_ros_setup $HOME/ros/groovy/
    export PATH=$PATH:`rospack find roseus`/bin
}

roshydrodev

if [ -e $HOME/prog/jsk-ros-pkg-unreleased ]; then
    export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$HOME/prog/jsk-ros-pkg-unreleased
fi

export EUSDIR=`rospack find euslisp`/jskeus/eus
export CVSDIR=$HOME/prog
export OPENHRPHOME=$HOME/prog/OpenHRP
export ROBOT=HRP2JSKNT
export HRP2NO=16
export ARCHDIR=Linux64

alias rtmlaunch='`rospack find hrpsys_ros_bridge`/scripts/rtmlaunch'

#export ROS_PARALLEL_JOBS=`grep -c processor /proc/cpuinfo`
if [ -e /proc/cpuinfo ]; then
    alias rosmake="rosmake --pjobs=`grep -c processor /proc/cpuinfo`"
fi

function rossetrobot() {
    local hostname=${1-"pr1012"}
    local ros_port=${2-"11311"}
    export ROS_MASTER_URI=http://$hostname:$ros_port
    echo -e "\e[1;31mset ROS_MASTER_URI to $ROS_MASTER_URI\e[m"
    rossetip
}
function rossetlocal() {
    rossetrobot localhost
    unset ROS_HOSTNAME
    unset ROS_IP
}


function rossetip() {
    export ROS_IP=`LANGUAGE=en LANG=C ifconfig | grep 'wlan|eth' -E -A 7 | grep inet\  | grep -v 127.0.0.1 | sed 's/.*inet addr:\([0-9\.]*\).*/\1/' | head -1`
    export ROS_HOSTNAME=$ROS_IP
    echo -e "\e[1;31mset ROS_IP and ROS_HOSTNAME to $ROS_IP\e[m"
}
if [ `which sw_vers > /dev/null 2>&1` ]; then
    rossetlocal
fi

#export HOMEBREW_CC=gcc

##################################################################
# oh my zsh
# Path to your oh-my-zsh configuration.

ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# af-magic candy jonathan
ZSH_THEME="af-magic"


# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git brew osx bower bundler mvn npm pip svn web-search)



# Customize to your needs...

function rosmaster_prompt() {
    local host
    host=`echo $ROS_MASTER_URI | sed -e 's%http://%%g'`
    echo $host
}

function catkin_ws_prompt() {
    echo $CATKIN_WS | sed -e "s%$HOME%~%g";
}

# load only one time
if [ "$TERM" != "dumb" ] ; then
    source /usr/local/lib/python2.7/dist-packages/powerline/bindings/zsh/powerline.zsh
    newline_replacer="s@__NEWLINE__@\n@g"
    export PROMPT="`echo $PROMPT | sed 's/)/ | sed $newline_replacer )/g'`
\$ "
fi
#export PROMPT=`echo $PROMPT`
# if [ "$TERM" != "dumb" -a "`echo $PS1 | grep -c POWERLINE`" = "0" ] ; then
#     source $ZSH/oh-my-zsh.sh
#     if [ "$OS" = "Darwin" ]; then # if osx
#         source /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
#     else
#         source /usr/local/lib/python2.7/dist-packages/powerline/bindings/zsh/powerline.zsh
#     fi
#     PS1="%F{006}[`rosmaster_prompt`] $FG[047][[`catkin_ws_prompt`]] $FG[014]%D{[%K:%M:%S]} $FG[014]Yes, Master? %{$reset_color%}
# $PS1
# \$ "
#     #RPROMPT='%F{006}%n$my_gray@$my_orange%m%{$reset_color%}%'
#     #RPROMPT="%{$(echotc UP 1)%}$RPS1%{$echotc DO 1}%}"
#     PROMPT2="%_%% "
#     SPROMPT="%r? べ, 別にあんたのために修正したんじゃないからね! [n,y,a,e]:"
# fi
### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# rvm use 1.9.2

export PATH=/Library/Haskell/bin:$PATH
alias pandocpdf="pandoc -V documentclass=ltjarticle --latex-engine=lualatex -t pdf"

export COOKIE_SECRET="hkfc-sakuchan"
export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"
export PATH="$PATH":/usr/local/share/python
alias ec="emacsclient -n"


export BASIC_USER="garaemon"
export BASIC_PASS="sakuchan"

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/mahout/bin:$PATH

# export JAVA_HOME=/Library/Java/Home
# export _JAVA_OPTIONS="-Dfile.encoding=UTF-8"

# source $HOME/gprog/maven-zsh-completion/_mvn

if [ -d $HOME/.rbenv/bin ]; then
    export RBENV_ROOT=$HOME/.rbenv
    export PATH="$RBENV_ROOT/bin:$PATH"
    eval "$(rbenv init -)"
    rbenv global 1.9.3-p448
    export PATH=$HOME/.rbenv/versions/1.9.3-p448/bin:$PATH
fi


export PATH=$PATH:$HOME/gprog/snapshotter/bin
export PATH=$PATH:$HOME/gprog/s3sync/

alias hdfs="hadoop fs"
export HADOOP_HEAPSIZE=2000
function restart-hadoop() {
    /usr/local/Cellar/hadoop/1.1.2/libexec/bin/stop-all.sh
    yes | hadoop namenode -format
    /usr/local/Cellar/hadoop/1.1.2/libexec/bin/start-all.sh
    hadoop dfsadmin -safemode leave 
}


function do_enter() {
    if [ -n "$BUFFER" ]; then
        zle accept-line
        return 0
    fi
    echo
    ls
    # ls_abbrev
    if [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" = 'true' ]; then
        echo
        echo -e "\e[0;33m--- git status ---\e[0m"
        git status --short --branch
    fi
    zle reset-prompt
    return 0
}
zle -N do_enter
bindkey '^m' do_enter

export RECOME_ENV=development-local

export PATH=$HOME/gprog/elastic-mapreduce-ruby:$PATH

source $HOME/.emacs.d/check_for_upgrade.sh

alias git-graph="git log --graph --decorate --oneline"

#percol settings

which percol > /dev/null
if [ $? ]; then
    # function percol_select_history() {
    #     local tac_cmd
    #     which gtac &> /dev/null && tac_cmd=gtac
    #     which tac &> /dev/null && tac_cmd=tac
    #     if [ `which sw_vers &> /dev/null` ]; then
    #         BUFFER=$(tail -r ~/.zsh_history | sed 's/^: [0-9]*:[0-9]*;//' \
    #             | percol --match-method regex --query "$LBUFFER")
    #     else
    #         BUFFER=$($tac_cmd ~/.zsh_history | sed 's/^: [0-9]*:[0-9]*;//' \
    #             | percol --match-method regex --query "$LBUFFER")
    #     fi
    #     CURSOR=$#BUFFER         # move cursor
    #     zle -R -c               # refresh
    # }
    # zle -N percol_select_history
    # bindkey '^R' percol_select_history

    function percol-select-history() {
        local tac
        if which tac > /dev/null; then
            tac="tac"
        else
            tac="tail -r"
        fi
        BUFFER=$(history -n 1 | \
            eval $tac | \
            percol --match-method regex --query "$LBUFFER")
        CURSOR=$#BUFFER
        zle clear-screen
    }
    zle -N percol-select-history
    bindkey '^r' percol-select-history

    function search-document-by-percol(){
        DOCUMENT_DIR="\
/path/to/doc/directory1
/path/to/doc/directory2"
        SELECTED_FILE=$(echo $DOCUMENT_DIR | xargs find | \
            grep -E "\.(pdf|txt|odp|odt|ods)$" | percol --match-method regex)
        if [ $? -eq 0 ]; then
            gnome-open $SELECTED_FILE
        fi
    }
    alias sd='search-document-by-percol'

    function insert-file-by-percol(){
        LBUFFER=$LBUFFER$(ls -A | percol --match-method regex | tr '\n' ' ' | \
            sed 's/[[:space:]]*$//') # delete trailing space
        zle -R -c
    }
    zle -N insert-file-by-percol
    bindkey '^[c' insert-file-by-percol
    
    function percol_select_dirstack_entry() {
        BUFFER=$(dirs -pl | percol --query "$LBUFFER")
        CURSOR=$#BUFFER
        zle -R -c
    }
    zle -N percol_select_dirstack_entry
    bindkey '^[d' percol_select_dirstack_entry
    
    alias p=percol
fi

function preexec_fluent() {
    curl -X POST -d 'json={"command":"'${1%% *}'"}' localhost:9880/zsh > /dev/null 2>&1
}
preexec_functions=(preexec_fluent)

export PATH=/usr/local/bin:/usr/local/share/python:$PATH
export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

# oh-my-zsh overwrite history
unalias history
# export JAVA_HOME=/usr/lib/jvm/java-6-openjdk

# added by travis gem
[ -f /home/jskuser/.travis/travis.sh ] && source /home/jskuser/.travis/travis.sh

function sine_wave() {
    i=0
    for i in `seq 0 10`
    do 
        SIN=$(python -c "from math import *;print map( lambda x: ceil(6*sin((x+$i)*pi/5)), range($(tput cols)) )" | tr -d '[]' | spark)
        echo -ne $SIN\\r 
        let i=i+1
        sleep 0.05
    done
    echo
}

if [ "$TERM" != "dumb" -a `which spark > /dev/null 2>&1` ] ; then
    sine_wave
fi

export TERM=xterm-256color

