- name: Install dictd packages
  ansible.builtin.apt: 
    name:
      - dictd
      - dict
      - dictfmt
  become: true
- name: Install dictd.conf
  ansible.builtin.copy:
    src: dictd.conf
    dest: /etc/dictd/dictd.conf
  become: true

- name: Check if systemd is running
  ansible.builtin.stat:
    path: /run/systemd/system
  register: systemd_check

- name: Restart dictd service
  ansible.builtin.systemd:
    name: dictd
    state: restarted
  become: true
  when: systemd_check.stat.exists
