- name: Install dictd packages
  apt:
    name:
      - dictd
      - dict
      - dictfmt
  become: true
- name: Install dictd.conf
  copy:
    src: dictd.conf
    dest: /etc/dictd/dictd.conf
  become: true
- name: restart dictd
  command: systemctl restart dictd
  become: true
