- name: Install dictd packages
  apt:
    name:
      - dictd
      - dict
      - dictfmt
  become: true
- name: Install dictd.conf
  copy:
    src: dictd.conf
    dest: /etc/dictd/dictd.conf
  become: true

- name: Check if systemd is running
  stat:
    path: /run/systemd/system
  register: dictd_systemd_check

- name: Restart dictd service
  systemd:
    name: dictd
    state: restarted
  become: true
  when: dictd_systemd_check.stat.exists
