- name: Create karabiner config directory
  file:
    path: ~/.config/karabiner
    state: directory
  when: ansible_os_family == "Darwin"

- name: Check if karabiner config exists
  stat:
    path: ~/.config/karabiner/karabiner.json
  register: karabiner_stat
  when: ansible_os_family == "Darwin"

- name: Check file differences for karabiner config
  command: diff ~/.config/karabiner/karabiner.json "{{ ghq_root_path }}/github.com/garaemon/garaemon-settings/roles/karabiner/files/karabiner.json"
  register: karabiner_diff
  failed_when: false
  changed_when: false
  when:
    - ansible_os_family == "Darwin"
    - karabiner_stat.stat.exists and not karabiner_stat.stat.islnk

- name: Remove existing karabiner config if identical to target
  file:
    path: ~/.config/karabiner/karabiner.json
    state: absent
  when:
    - ansible_os_family == "Darwin"
    - karabiner_stat.stat.exists
    - not karabiner_stat.stat.islnk
    - karabiner_diff.rc == 0

- name: Create symlink for karabiner configuration
  file:
    src: "{{ ghq_root_path }}/github.com/garaemon/garaemon-settings/roles/karabiner/files/karabiner.json"
    dest: ~/.config/karabiner/karabiner.json
    state: link
  when: ansible_os_family == "Darwin"
