palette = "solarized_dark"

format = """
[](violet)\
$os\
$username\
$hostname\
[](bg:magenta fg:violet)\
$directory\
[](fg:magenta bg:orange)\
$git_branch\
$git_status\
[](fg:orange)
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](fg:blue bg:cyan)\
$docker_context\
[](fg:cyan bg:blue)\
${custom.chezmoi}\
[](fg:blue)
$time\
[](fg:base01 bg:red)\
$cmd_duration\
[ ](fg:red) $character
\\$ """

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[✓](bold cyan)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✘](bold red)'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:violet"
style_root = "bg:violet"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = false
format = '[on $ssh_symbol$hostname]($style)'
style = "bg:violet"

# The default "dimmed" color is too dark for me.
# style ="green bold"

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:violet"
disabled = true # Disabled by default

[directory]
style = "bg:magenta fg:base03"
format = "[ $path ]($style)"
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:cyan"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:orange fg:white"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:orange fg:white"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:base01"
format = '[ ♥ $time ]($style)'

[python]
# Remove "via" from the original format
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'
style = "bg:base03"

[cmd_duration]
format = '[ took $duration]($style)'
style = "bg:red"

[custom.chezmoi]
when = ''' test "$CHEZMOI" = "1" '''
style = "bg:blue"
format = "[chezmoi shell]($style)"

[palettes.solarized_dark]
base03 = "#002b36"
base02 = "#073642"
base01 = "#586e75"
base00 = "#657b83"
base0 = "#839496"
base1 = "#93a1a1"
base2 = "#eee8d5"
base3 = "#fdf6e3"
yellow = "#b58900"
orange = "#cb4b16"
red = "#dc322f"
magenta = "#d33682"
violet = "#6c71c4"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
