- name: Configure Ghostty on Darwin
  when: ansible_os_family == 'Darwin'
  block:

    - name: Make directory for config
      file:
        path: "{{ ansible_env.HOME }}/Library/Application Support/com.mitchellh.ghostty"
        state: directory
        mode: "0755"

    - name: Check if ghostty config exists and is not a symlink
      stat:
        path: "{{ ansible_env.HOME }}/Library/Application Support/com.mitchellh.ghostty/config"
      register: ghostty_config_stat
      failed_when: ghostty_config_stat.stat.exists and not ghostty_config_stat.stat.islnk

    - name: Create symlink for ghostty config
      file:
        src: ~/gprog/garaemon-settings/roles/ghostty/files/config
        dest: "{{ ansible_env.HOME }}/Library/Application Support/com.mitchellh.ghostty/config"
        state: link
