---

- name: Install pyenv build requirements with Homebrew
  package:
    name: "{{ pyenv_build_requirements }}"

- name: Install pyenv with Homebrew
  package:
    name: pyenv

- name: Install pyenv-virtualenv with Homebrew
  package:
    name: pyenv-virtualenv

- name: Install pyenv-virtualenvwrapper with Homebrew
  package:
    name: pyenv-virtualenvwrapper
  when: pyenv_virtualenvwrapper
