---
# tasks file for ansible-pyenv

- name: Load variables for the target system
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- ansible.builtin.include_tasks: Linux.yml
  when: "ansible_system == 'Linux'"

- ansible.builtin.include_tasks: Darwin.yml
  when: "ansible_os_family == 'Darwin'"

- ansible.builtin.include_tasks: install.yml

- ansible.builtin.include_tasks: shell.yml
  when: pyenv_init_shell
