- name: Import base playbook
  import_playbook: main.yml

- name: Apply ax8-max specific settings
  hosts: all
  roles:
    - role: fingerprint_mafp
      when: ansible_facts.os_family == "Debian" and ansible_facts.architecture == "x86_64"
