- name: "Install clang-tools-6.0"
  apt:
    name:
      - clang-tools-6.0
  when: ansible_os_family == "Debian"
  become: yes
- name: "Install clangd update-alternatives"
  command: update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-6.0 60
  when: ansible_os_family == "Debian"
  become: yes
- name: "Install clangd update-alternatives"
  command: update-alternatives --set clangd /usr/bin/clangd-6.0
  when: ansible_os_family == "Debian"
  become: yes
