- name: "Install clang-tools-6.0"
  ansible.builtin.apt: 
    name:
      - clang-tools-6.0
  when: ansible_os_family == "Debian"
  become: true
- name: "Install clangd update-alternatives"
  ansible.builtin.command: update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-6.0 60
  when: ansible_os_family == "Debian"
  become: true
- name: "Install clangd update-alternatives"
  ansible.builtin.command: update-alternatives --set clangd /usr/bin/clangd-6.0
  when: ansible_os_family == "Debian"
  become: true
