- name: Get ghq root directory
  command: ghq root
  register: claude_ghq_root
  changed_when: false
  failed_when: false

- name: Set ghq root path
  set_fact:
    claude_ghq_root_path: "{{ claude_ghq_root.stdout if claude_ghq_root.rc == 0 else ansible_env.HOME + '/ghq' }}"

- name: Ensure .claude directory exists
  file:
    path: ~/.claude
    state: directory
    mode: '0755'

- name: Check if CLAUDE.md exists
  stat:
    path: ~/.claude/CLAUDE.md
  register: claude_md_stat


# TODO: it does not work if we run this role for a different host
- name: Check file differences for CLAUDE.md
  command: diff ~/.claude/CLAUDE.md "{{ claude_ghq_root_path }}/github.com/garaemon/garaemon-settings/roles/claude/files/CLAUDE.md"
  register: claude_md_diff
  failed_when: false
  changed_when: false
  when: claude_md_stat.stat.exists and not claude_md_stat.stat.islnk

- name: Remove existing CLAUDE.md if identical to target
  file:
    path: ~/.claude/CLAUDE.md
    state: absent
  when:
    - claude_md_stat.stat.exists
    - not claude_md_stat.stat.islnk
    - claude_md_diff.rc == 0

- name: Create symlink for CLAUDE.md
  file:
    src: "{{ claude_ghq_root_path }}/github.com/garaemon/garaemon-settings/roles/claude/files/CLAUDE.md"
    dest: ~/.claude/CLAUDE.md
    state: link

- name: Ensure .claude/commands directory exists
  file:
    path: ~/.claude/commands
    state: directory
    mode: '0755'

- name: Check if create-pr.md exists
  stat:
    path: ~/.claude/commands/create-pr.md
  register: claude_create_pr_stat

- name: Check file differences for create-pr.md
  command: diff ~/.claude/commands/create-pr.md "{{ claude_ghq_root_path }}/github.com/garaemon/garaemon-settings/roles/claude/files/create-pr.md"
  register: claude_create_pr_diff
  failed_when: false
  changed_when: false
  when: claude_create_pr_stat.stat.exists and not claude_create_pr_stat.stat.islnk

- name: Remove existing create-pr.md if identical to target
  file:
    path: ~/.claude/commands/create-pr.md
    state: absent
  when:
    - claude_create_pr_stat.stat.exists
    - not claude_create_pr_stat.stat.islnk
    - claude_create_pr_diff.rc == 0

- name: Create symlink for create-pr.md
  file:
    src: "{{ claude_ghq_root_path }}/github.com/garaemon/garaemon-settings/roles/claude/files/create-pr.md"
    dest: ~/.claude/commands/create-pr.md
    state: link

- name: Install Claude Code via mise
  command: mise use -g claude
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  retries: 3
  delay: 5
  register: claude_claude_install_result
  until: claude_claude_install_result.rc == 0
